name = "XPalm"
uuid = "6b523e1e-d512-416c-8e51-a8fbef0064e7"
version = "0.5.1"
authors = ["RÃ©mi Vezy <VEZY@users.noreply.github.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PlantGeom = "5edaa67e-25db-4eb9-bf81-05d793b2238d"
PlantMeteo = "4630fe09-e0fb-4da5-a846-781cb73437b6"
PlantSimEngine = "9a576370-710b-4269-adf9-4f603a9c6423"
PlyIO = "42171d58-473b-503a-8d5f-782019eb09ec"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TransformsBase = "28dd2a49-a57a-4bfb-84ca-1a49db9b96b8"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[weakdeps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[extensions]
XPalmPluto = "Pluto"

[compat]
Coverage = "0.7.0, 1"
Dates = "1"
Interpolations = "0.15.1, 0.16"
Meshes = "0.54, 0.56"
MultiScaleTreeGraph = "0.14.4"
OrderedCollections = "1.6"
PlantGeom = "0.14.1, 0.15"
PlantMeteo = "0.6.0, 0.7"
PlantSimEngine = "0.13"
Pluto = "0.20"
PlyIO = "1.2.0"
Random = "1"
Rotations = "1"
Statistics = "1"
Tables = "1.12"
Test = "1"
TransformsBase = "1.6.0"
Unitful = "1.22.0"
YAML = "0.4"
julia = "1.10"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Coverage"]
