name = "XPalmModel"
uuid = "6b523e1e-d512-416c-8e51-a8fbef0064e7"
authors = ["RÃ©mi Vezy <VEZY@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
PlantMeteo = "4630fe09-e0fb-4da5-a846-781cb73437b6"
PlantSimEngine = "9a576370-710b-4269-adf9-4f603a9c6423"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[extensions]
XPalmPluto = "Pluto"

[compat]
Dates = "1"
MultiScaleTreeGraph = "0.14.1"
PlantMeteo = "0.6.0"
PlantSimEngine = "0.11"
Pluto = "0.20"
Random = "1"
Statistics = "1"
Tables = "1.12"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
